### PR TITLE
Feature/grid related fixes

### PR DESCRIPTION
**Pull request by anoack93**
Currently we are working on a nuxt integration for the aem spa editor which is based on your vue integration (thanks for your effort).
Due to issues with the AEM Grid we created an internal fork of your package and fixed the missing grid css classes.
However, you were a little bit faster and already released a fix yourself, but we added a few improvements in which you might be interessted, this includes:

* minor code style fixes and cosmetic changes
* we replaced Utils.modelToProps calls with super method calls like in the react package
* minor fix in Container.ts (wrong use of Array.map)

I hope this helps you a little bit, keep up your good work!

If you like, we can also get in touch to work together on a better vue support.

### CODE REVIEW

**Review by wmblocker — APPROVED** [review]

**Review by wmblocker — CHANGES_REQUESTED** [review]
[8bd2ceb](https://github.com/mavicellc/aem-vue-editable-components/pull/1/commits/8db2ceb45318dbc0c94f9ae11005ff75ee7b82d9) This achieves the same goal as the cqItemsOrder.map function call. The difference between this implementation and ours is that you are declaring a local variable to store the childComponents while we are just returning a new array with the map function.

**Review by wmblocker — COMMENTED** [review]
[4ac5ef3](https://github.com/mavicellc/aem-vue-editable-components/pull/1/commits/4ac5ef3d4739a5d20faaae4cd5cd6c2115a381b2) Nice!

**Comment by anoack93** [comment]
> [8bd2ceb](https://github.com/mavicellc/aem-vue-editable-components/pull/1/commits/8db2ceb45318dbc0c94f9ae11005ff75ee7b82d9) This achieves the same goal as the cqItemsOrder.map function call. The difference between this implementation and ours is that you are declaring a local variable to store the childComponents while we are just returning a new array with the map function.

I think the result is not exact the same. The Array.prototype.map function is designed to return an array with the same size like the original array. But in your code you are also apply some kind of filter. In some cases you are not having any *return* statement. I am not sure what map is doing in these cases but probably it will be equal to return `undefined`.
So I think it is better to explicitly push elements into the array. This combines mapping and filtering and you don't have null or undefined values in your resulting array.

**Comment by anoack93** [comment]
I will close this Pull Request because I think the changes are outdated.

**Pull request closed without merging**
